---
- name: Deploy Flask App with Docker
  hosts: all
  become: true

  tasks:
    - name: Create app directory on EC2
      file:
        path: ~/app
        state: directory
        mode: '0755'

    - name: Copy app files to EC2 (including Dockerfile, app.py, templates, and docker-compose.yml)
      copy:
        src: ../app/
        dest: ~/app/
        mode: '0755'

    - name: Remove old Docker container if running
      shell: |
        docker rm -f flask-app || true

    - name: Build Docker image
      shell: |
        cd ~/app
        docker build -t flask-app .

    - name: Run Docker container
      shell: |
        docker run -d --name flask-app -p 5000:5000 flask-app
