---
- name: Deploy Flask App with Docker
  hosts: web
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        creates: /usr/local/bin/docker-compose

    - name: Clone or update app
      ansible.builtin.git:
        repo: 'https://github.com/CHRISTUPREMCHANDNEELA/collegeFeedback.git'
        dest: /home/ubuntu/app
        force: yes

    - name: Deploy Docker containers
      shell: |
        cd /home/ubuntu/app
        docker-compose down || true
        docker-compose build
        docker-compose up -d
